<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Delivery at:') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <?php 
            	$deliveryat = $this->getDeliveryAt();
            ?>
            <tr>
                <td class="value"><?php echo $deliveryat;?></td>
            </tr>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>